### ISSUE TITLE
链接似乎失效

### ISSUE THREAD

**Issue by dgzens** [GenshinMinecraft/SQAIPAD-V11_Official_Images#1]
我Root了v11这个平板，却忘记备份原来的镜像文件，不小心失手操作现在卡在fastboot界面，您这儿的镜像又访问不了，只有boot两个的，请问一下有没有镜像包下载，谢谢！

**Comment by GenshinMinecraft** [comment]
请稍等，我马上发你一份

**Comment by GenshinMinecraft** [comment]
链接失效是因为博客换域名了，不好意思

**Comment by GenshinMinecraft** [comment]
http://vooid.link/SQAI%20ALL%20PART.zip

这是我之前存的一份刷机包，除了userdata都有了，希望能对你有所帮助


> 我Root了v11这个平板，却忘记备份原来的镜像文件，不小心失手操作现在卡在fastboot界面，您这儿的镜像又访问不了，只有boot两个的，请问一下有没有镜像包下载，谢谢！
